# config/tasks.yaml
research_task:
  description: >
    Conduct a thorough research about {query}.
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {query}
  agent: researcher

reporting_task:
  description: >
    Review the research about {query} and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics about {query}, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: report.md