"""Initial_migration

Revision ID: e95a19e47c6b
Revises: c7ab3ff181ea
Create Date: 2024-11-17 06:08:19.866388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95a19e47c6b'
down_revision: Union[str, None] = 'c7ab3ff181ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
